name: ljy_rag_ft
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - blas=1.0
  - bzip2=1.0.8
  - ca-certificates=2026.1.4
  - cuda-cudart=12.9.79
  - cuda-cudart_linux-64=12.9.79
  - cuda-nvrtc=12.9.86
  - cuda-version=12.9
  - cudnn=9.10.2.21
  - expat=2.7.4
  - icu=73.1
  - idna=3.11
  - intel-openmp=2025.0.0
  - joblib=1.5.3
  - ld_impl_linux-64=2.44
  - libcublas=12.9.1.4
  - libcudnn=9.10.2.21
  - libcudnn-dev=9.10.2.21
  - libcusolver=11.7.5.82
  - libcusparse=12.5.10.65
  - libexpat=2.7.4
  - libffi=3.4.4
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgfortran=15.2.0
  - libgfortran-ng=15.2.0
  - libgfortran5=15.2.0
  - libgomp=15.2.0
  - libhwloc=2.12.1
  - libnsl=2.0.0
  - libnvjitlink=12.9.86
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libuuid=1.41.5
  - libxcb=1.17.0
  - libxml2=2.13.9
  - libzlib=1.3.1
  - mkl=2025.0.0
  - mkl-service=2.5.2
  - mkl_fft=2.1.1
  - mkl_random=1.3.0
  - ncurses=6.5
  - numpy-base=2.2.5
  - openssl=3.6.1
  - pip=25.3
  - pthread-stubs=0.3
  - python=3.10.19
  - python_abi=3.10
  - readline=8.3
  - scikit-learn=1.7.2
  - scipy=1.15.3
  - setuptools=80.10.2
  - sqlite=3.51.1
  - tbb=2022.3.0
  - tbb-devel=2022.3.0
  - tk=8.6.15
  - tzdata=2025c
  - wheel=0.46.3
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - yaml=0.2.5
  - zlib=1.3.1
  - pip:
      - absl-py==2.4.0
      - accelerate==1.12.0
      - addict==2.4.0
      - aiofiles==24.1.0
      - aliyun-python-sdk-core==2.16.0
      - aliyun-python-sdk-kms==2.16.5
      - annotated-doc==0.0.4
      - anthropic==0.79.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.12.1
      - apache-tvm-ffi==0.1.8.post2
      - astor==0.8.1
      - async-timeout==4.0.3
      - attrdict==2.0.1
      - attrs==25.4.0
      - binpacking==2.0.1
      - blake3==1.0.8
      - brotli==1.2.0
      - cachetools==7.0.1
      - cbor2==5.8.0
      - certifi==2026.1.4
      - cffi==2.0.0
      - click==8.3.1
      - cloudpickle==3.1.2
      - compressed-tensors==0.13.0
      - cpm-kernels==1.0.11
      - crcmod==1.7
      - cryptography==46.0.5
      - cuda-bindings==13.1.1
      - cuda-python==13.1.1
      - cupy-cuda12x==13.6.0
      - dacite==1.9.2
      - dataclasses-json==0.6.7
      - datasets==3.6.0
      - depyf==0.20.0
      - dill==0.3.8
      - diskcache==5.6.3
      - distro==1.9.0
      - dnspython==2.8.0
      - docstring-parser==0.17.0
      - einops==0.8.2
      - email-validator==2.3.0
      - eventlet==0.40.4
      - exceptiongroup==1.3.1
      - fastapi==0.128.7
      - fastapi-cli==0.0.20
      - fastapi-cloud-cli==0.11.0
      - fastar==0.8.0
      - fastrlock==0.8.3
      - ffmpy==1.0.0
      - filelock==3.20.3
      - flashinfer-python==0.6.1
      - fsspec==2025.3.0
      - gguf==0.17.1
      - gradio==5.50.0
      - gradio-client==1.14.0
      - greenlet==3.3.1
      - groovy==0.1.2
      - grpcio==1.78.0
      - grpcio-reflection==1.78.0
      - h11==0.16.0
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httptools==0.7.1
      - httpx==0.28.1
      - httpx-sse==0.4.3
      - huggingface-hub==0.36.2
      - ijson==3.4.0.post0
      - importlib-metadata==8.7.1
      - interegular==0.3.3
      - jieba==0.42.1
      - jinja2==3.1.6
      - jmespath==0.10.0
      - json-repair==0.57.1
      - jsonpatch==1.33
      - jsonpointer==3.0.0
      - jsonschema==4.26.0
      - jsonschema-specifications==2025.9.1
      - langchain==1.2.10
      - langchain-classic==1.0.1
      - langchain-community==0.4.1
      - langchain-core==1.2.11
      - langchain-text-splitters==1.1.0
      - langgraph==1.0.8
      - langgraph-checkpoint==4.0.0
      - langgraph-prebuilt==1.0.7
      - langgraph-sdk==0.3.5
      - langsmith==0.7.1
      - lark==1.2.2
      - llguidance==1.3.0
      - llvmlite==0.44.0
      - lm-format-enforcer==0.11.3
      - loguru==0.7.3
      - lxml==6.0.2
      - markdown==3.10.2
      - markdown-it-py==4.0.0
      - markupsafe==3.0.3
      - marshmallow==3.26.2
      - mcp==1.26.0
      - mdurl==0.1.2
      - mistral-common==1.9.0
      - model-hosting-container-standards==0.1.13
      - modelscope==1.34.0
      - ms-swift==3.12.4
      - msgpack==1.1.2
      - msgspec==0.20.0
      - multiprocess==0.70.16
      - mypy-extensions==1.1.0
      - ninja==1.13.0
      - nltk==3.9.2
      - numba==0.61.2
      - numpy==2.2.6
      - nvidia-cudnn-frontend==1.18.0
      - nvidia-cutlass-dsl==4.3.5
      - nvidia-ml-py==13.590.48
      - nvidia-nvshmem-cu12==3.3.20
      - omegaconf==2.3.0
      - openai-harmony==0.0.8
      - opencv-python-headless==4.13.0.92
      - orjson==3.11.7
      - ormsgpack==1.12.2
      - oss2==2.19.1
      - outlines-core==0.2.11
      - packaging==26.0
      - partial-json-parser==0.2.1.1.post7
      - pastedeploy==3.1.0
      - peft==0.18.1
      - pillow==11.3.0
      - prometheus-client==0.24.1
      - prometheus-fastapi-instrumentator==7.1.0
      - protobuf==6.33.5
      - psutil==7.2.2
      - py-cpuinfo==9.0.0
      - pybase64==1.4.3
      - pycountry==24.6.1
      - pycparser==3.0
      - pycryptodome==3.23.0
      - pydantic==2.12.3
      - pydantic-core==2.41.4
      - pydantic-extra-types==2.11.0
      - pydantic-settings==2.12.0
      - pydub==0.25.1
      - pyeclib==1.7.0
      - pygments==2.19.2
      - pyjwt==2.11.0
      - python-json-logger==4.0.0
      - python-multipart==0.0.22
      - pytz==2025.2
      - pyyaml==6.0.3
      - pyzmq==27.1.0
      - ray==2.53.0
      - referencing==0.37.0
      - regex==2026.1.15
      - requests-toolbelt==1.0.0
      - rich==14.3.2
      - rich-toolkit==0.19.2
      - rignore==0.7.6
      - rouge==1.0.1
      - rpds-py==0.30.0
      - ruff==0.15.0
      - safehttpx==0.1.7
      - safetensors==0.7.0
      - semantic-version==2.10.0
      - sentencepiece==0.2.1
      - sentry-sdk==2.52.0
      - setproctitle==1.3.7
      - shellingham==1.5.4
      - simplejson==3.20.2
      - six==1.17.0
      - sortedcontainers==2.4.0
      - sqlalchemy==2.0.46
      - sse-starlette==3.2.0
      - starlette==0.52.1
      - supervisor==4.3.0
      - swift==2.37.0
      - tabulate==0.9.0
      - tenacity==9.1.4
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - threadpoolctl==3.6.0
      - tiktoken==0.12.0
      - tokenizers==0.22.2
      - tomli==2.4.0
      - tomlkit==0.13.3
      - torch==2.3.1+cpu
      - torchaudio==2.3.1+cpu
      - torchvision==0.18.1+cpu
      - tqdm==4.67.3
      - transformers==4.57.6
      - transformers-stream-generator==0.0.5
      - triton==3.5.1
      - trl==0.24.0
      - typer==0.22.0
      - typer-slim==0.21.1
      - typing-extensions==4.15.0
      - typing-inspect==0.9.0
      - urllib3==2.6.3
      - uuid-utils==0.14.0
      - uvicorn==0.40.0
      - uvloop==0.22.1
      - vllm==0.15.1
      - watchfiles==1.1.1
      - websockets==15.0.1
      - werkzeug==3.1.5
      - xattr==1.3.0
      - xgrammar==0.1.29
      - zipp==3.23.0
      - zstandard==0.25.0
prefix: /home/jyliu/miniconda3/envs/ljy_rag_ft
